#!/usr/bin/python3
import sys
from src.error_handling import *
from src.maths import *
from src.matrix_operations import *

def main(args):
    nb_args = len(args)

    if nb_args == 2 and args[1] == "-h":
        print("USAGE\n\t./108trigo fun a0 a1 a2 ...\nDESCRIPTION\n\tfun\tfunction to be applied, among at least \"EXP\", \"COS\", \"SIN\", \"COSH\" and \"SINH\"\n\tai\tcoeficients of the matrix")
        exit(0)
    elif nb_args < 6:
        display_error("Not enough arguments, takes a minimum of six arguments.")
        exit(84)
    detect_function(args)

if __name__ == '__main__':
    main(sys.argv)